export const MOCK_ODS = [
  {
    id: "1",
    type: "Individual",
    status: "Approved",
    date: "2024-03-15",
    eventTitle: "Technical Workshop on React Native",
    organizer: "Google Developer Student Clubs",
    description:
      "Attending a full-day workshop on React Native development and best practices. Will learn about Expo, Navigation, and State Management.",
    startTime: "09:00 AM",
    endTime: "05:00 PM",
    venue: "Main Auditorium",
    appliedDate: "2024-03-10",
    approvalFlow: [
      { role: "Class Advisor", status: "Approved", date: "2024-03-10" },
      { role: "HOD", status: "Approved", date: "2024-03-11" },
    ],
  },
  {
    id: "2",
    type: "Team",
    status: "Pending",
    date: "2024-03-20",
    eventTitle: "Inter-College Hackathon",
    organizer: "Tech Society",
    description:
      "Participating in a 24-hour hackathon as a team of 4. Project theme: AI for Social Good.",
    startTime: "08:00 AM",
    endTime: "08:00 AM (Next Day)",
    venue: "Innovation Hub",
    teamMembers: [
      { name: "John Doe", rollNo: "CS2101" },
      { name: "Jane Smith", rollNo: "CS2105" },
      { name: "Mike Johnson", rollNo: "CS2110" },
      { name: "Sarah Wilson", rollNo: "CS2115" },
    ],
    appliedDate: "2024-03-12",
    approvalFlow: [
      { role: "Class Advisor", status: "Approved", date: "2024-03-12" },
      { role: "HOD", status: "Pending", date: null },
    ],
  },
  {
    id: "3",
    type: "Individual",
    status: "Rejected",
    date: "2024-03-05",
    eventTitle: "Sports Meet",
    organizer: "Physical Education Dept",
    description:
      "Representing the department in Inter-Department Cricket Tournament.",
    startTime: "02:00 PM",
    endTime: "06:00 PM",
    venue: "College Ground",
    rejectionReason: "Insufficient attendance in previous classes.",
    appliedDate: "2024-03-01",
  },
  {
    id: "4",
    type: "Team",
    status: "Approved",
    date: "2024-02-28",
    eventTitle: "Paper Presentation",
    organizer: "IEEE Student Branch",
    description:
      "Presenting a paper on 'Sustainable Computing' at the National Conference.",
    startTime: "10:00 AM",
    endTime: "01:00 PM",
    venue: "Seminar Hall 2",
    teamMembers: [
      { name: "John Doe", rollNo: "CS2101" },
      { name: "Robert Brown", rollNo: "CS2120" },
    ],
    appliedDate: "2024-02-20",
  },
];
